### ISSUE TITLE
Fixing `add_fixed_in_frame_mobjects`

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#569]
```py
class Text3D(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes()
        self.set_camera_orientation(phi=75 * DEGREES,theta=-45*DEGREES)
        text=TextMobject("This is a 3D text")
        self.add_fixed_in_frame_mobjects(text.to_corner(UL))
        self.add(axes)
        self.add(text)
        self.wait()
  ```
This script is currently broken because add_fixed_in_frame_mobjects throws an error.
It was broken before but fixed by https://github.com/ManimCommunity/manim/pull/281.
Now, with `git bisect` I could boil down the first occurrence of this error to this pr:
https://github.com/ManimCommunity/manim/pull/532 (ping to @eulertour)
Before that, the Text3D Scene was functioning properly.
It would be nice when we could make this work again :)
As soon as we have it fixed, I can volunteer to add a test for this.

**Comment by BrendanMartin** [comment]
Yeah, I was getting the error:
```AttributeError: 'ThreeDCamera' object has no attribute 'extract_mobject_family_members'```
and found in #532 there's a change to camera.py where `extract_mobject_family_members` was moved:
https://github.com/ManimCommunity/manim/pull/532/files#diff-7732083ebe3bdfdbb948a293a8ff761e5c4a7b8ed98e1daed6838076a4781234L366

**Comment by behackl** [comment]
Fixed via #674.
