### ISSUE TITLE
circuiTikz won't compile in v0.7

### ISSUE THREAD

**Issue by Ribisl** [ManimCommunity/manim#1618]
I updated to version 0.7 today and noticed, that my circuiTikz latex won't compile anymore

Error code:
`[06/02/21 19:29:14] ERROR    LaTeX compilation error: {log[error_pos][2:])}                                                                tex_file_writing.py:198                    ERROR    Context for error:                                                                                            tex_file_writing.py:223
                             \begin{circuitikz}[european,straight voltages]
                                       \draw
                                       (0,0) to [R=$R_3$] (0,2)
                                       to [C,C=C, i_<=$\underline{I}_1$](-2,2);
                                       \draw (0,2)
                                       to[short,i_<=$\underline{I}_2$] (2,2);
                                       \draw (0,0) to [short] (2,0);
                                       \draw (0,0) to [short] (-2,0);
                                       \draw (2,2) to [open,v_=$\underline{U}_2$] (2,0);
                                       \draw (-2,2) to [open,v_=$\underline{U}_1$] (-2,0);
                                       \end{circuitikz}
                             \end{align*}
                             ^ this line`

In v0.6 they worked fine, except that you had to change the opacity and the stroke to get acceptable results

**Comment by kilacoda** [comment]
Could you share the contents of the `.log` file? The one that's mentioned at the end of the traceback.

**Comment by Ribisl** [comment]
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.3) (preloaded format=latex 2021.6.1)  2 JUN 2021 20:41
entering extended mode
**./media/Tex/d4d6a6fd809d8da4.tex
(media/Tex/d4d6a6fd809d8da4.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-05-27> (F:\ProgramData\Miktex2\tex/latex/standalone\
standalone.cls
Document Class: standalone 2018/03/26 v1.3a Class to compile TeX sub-files stan
dalone
(F:\ProgramData\Miktex2\tex/latex/latex-tools\shellesc.sty
Package: shellesc 2019/11/08 v1.0c unified shell escape interface for LaTeX
Package shellesc Info: Restricted shell escape enabled on input line 77.
) (F:\ProgramData\Miktex2\tex/generic/iftex\ifluatex.sty
Package: ifluatex 2019/10/25 v1.5 ifluatex legacy package. Use iftex instead.
(F:\ProgramData\Miktex2\tex/generic/iftex\iftex.sty
Package: iftex 2020/03/06 v1.0d TeX engine tests
)) (F:\ProgramData\Miktex2\tex/latex/xkeyval\xkeyval.sty
Package: xkeyval 2020/11/20 v2.8 package option processing (HA)
(F:\ProgramData\Miktex2\tex/generic/xkeyval\xkeyval.tex (F:\ProgramData\Miktex2
\tex/generic/xkeyval\xkvutils.tex
\XKV@toks=\toks15
\XKV@tempa@toks=\toks16
(F:\ProgramData\Miktex2\tex/generic/xkeyval\keyval.tex))
\XKV@depth=\count181
File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
))
\sa@internal=\count182
\c@sapage=\count183
(F:\ProgramData\Miktex2\tex/latex/standalone\standalone.cfg
File: standalone.cfg 2018/03/26 v1.3a Default configuration file for 'standalon
e' class
) (F:\ProgramData\Miktex2\tex/latex/base\article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(F:\ProgramData\Miktex2\tex/latex/base\size10.clo
File: size10.clo 2020/04/10 v1.4m Standard LaTeX file (size option)
)
\c@part=\count184
\c@section=\count185
\c@subsection=\count186
\c@subsubsection=\count187
\c@paragraph=\count188
\c@subparagraph=\count189
\c@figure=\count190
\c@table=\count191
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen138
) (F:\ProgramData\Miktex2\tex/latex/preview\preview.sty
Package: preview 2017/04/24 12.3 (AUCTeX/preview-latex)
(F:\ProgramData\Miktex2\tex/generic/luatex85\luatex85.sty
Package: luatex85 2016/06/15 v1.4 pdftex aliases for luatex
) (F:\ProgramData\Miktex2\tex/latex/preview\prtightpage.def
\PreviewBorder=\dimen139
)
\pr@snippet=\count192
\pr@box=\box47
\pr@output=\toks17
)) (F:\ProgramData\Miktex2\tex/generic/babel\babel.sty
Package: babel 2021/05/16 3.59 The Babel package
(F:\ProgramData\Miktex2\tex/generic/babel\babel.def
File: babel.def 2021/05/16 3.59 Babel common definitions
\babel@savecnt=\count193
\U@D=\dimen140
\l@unhyphenated=\language79
(F:\ProgramData\Miktex2\tex/generic/babel\txtbabel.def)
\bbl@readstream=\read2
)
\bbl@dirlevel=\count194
*************************************
* Local config file bblopts.cfg used
*
(F:\ProgramData\Miktex2\tex/latex/arabi\bblopts.cfg
File: bblopts.cfg 2005/09/08 v0.1 add Arabic and Farsi to "declared" options of
 babel
) (F:\ProgramData\Miktex2\tex/latex/babel-english\english.ldf
Language: english 2017/06/06 v3.3r English support from the babel system
Package babel Info: Hyphen rules for 'canadian' set to \l@english
(babel)             (\language0). Reported on input line 102.
Package babel Info: Hyphen rules for 'australian' set to \l@ukenglish
(babel)             (\language73). Reported on input line 105.
Package babel Info: Hyphen rules for 'newzealand' set to \l@ukenglish
(babel)             (\language73). Reported on input line 108.
)) (F:\ProgramData\Miktex2\tex/latex/base\inputenc.sty
Package: inputenc 2020/08/01 v1.3d Input encoding file
\inpenc@prehook=\toks18
\inpenc@posthook=\toks19
) (F:\ProgramData\Miktex2\tex/latex/base\fontenc.sty
Package: fontenc 2020/08/10 v2.0s Standard LaTeX package
) (F:\ProgramData\Miktex2\tex/latex/lm\lmodern.sty
Package: lmodern 2009/10/30 v1.6 Latin Modern Fonts
LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
(Font)                  OT1/cmr/m/n --> OT1/lmr/m/n on input line 22.
LaTeX Font Info:    Overwriting symbol font `letters' in version `normal'
(Font)                  OML/cmm/m/it --> OML/lmm/m/it on input line 23.
LaTeX Font Info:    Overwriting symbol font `symbols' in version `normal'
(Font)                  OMS/cmsy/m/n --> OMS/lmsy/m/n on input line 24.
LaTeX Font Info:    Overwriting symbol font `largesymbols' in version `normal'
(Font)                  OMX/cmex/m/n --> OMX/lmex/m/n on input line 25.
LaTeX Font Info:    Overwriting symbol font `operators' in version `bold'
(Font)                  OT1/cmr/bx/n --> OT1/lmr/bx/n on input line 26.
LaTeX Font Info:    Overwriting symbol font `letters' in version `bold'
(Font)                  OML/cmm/b/it --> OML/lmm/b/it on input line 27.
LaTeX Font Info:    Overwriting symbol font `symbols' in version `bold'
(Font)                  OMS/cmsy/b/n --> OMS/lmsy/b/n on input line 28.
LaTeX Font Info:    Overwriting symbol font `largesymbols' in version `bold'
(Font)                  OMX/cmex/m/n --> OMX/lmex/m/n on input line 29.
LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `normal'
(Font)                  OT1/cmr/bx/n --> OT1/lmr/bx/n on input line 31.
LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `normal'
(Font)                  OT1/cmss/m/n --> OT1/lmss/m/n on input line 32.
LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `normal'
(Font)                  OT1/cmr/m/it --> OT1/lmr/m/it on input line 33.
LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `normal'
(Font)                  OT1/cmtt/m/n --> OT1/lmtt/m/n on input line 34.
LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `bold'
(Font)                  OT1/cmr/bx/n --> OT1/lmr/bx/n on input line 35.
LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `bold'
(Font)                  OT1/cmss/bx/n --> OT1/lmss/bx/n on input line 36.
LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `bold'
(Font)                  OT1/cmr/bx/it --> OT1/lmr/bx/it on input line 37.
LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `bold'
(Font)                  OT1/cmtt/m/n --> OT1/lmtt/m/n on input line 38.
) (F:\ProgramData\Miktex2\tex/latex/amsmath\amsmath.sty
Package: amsmath 2020/09/23 v2.17i AMS math features
\@mathmargin=\skip49
For additional information on amsmath, use the `?' option.
(F:\ProgramData\Miktex2\tex/latex/amsmath\amstext.sty
Package: amstext 2000/06/29 v2.01 AMS text
(F:\ProgramData\Miktex2\tex/latex/amsmath\amsgen.sty
File: amsgen.sty 1999/11/30 v2.0 generic functions
\@emptytoks=\toks20
\ex@=\dimen141
)) (F:\ProgramData\Miktex2\tex/latex/amsmath\amsbsy.sty
Package: amsbsy 1999/11/29 v1.2d Bold Symbols
\pmbraise@=\dimen142
) (F:\ProgramData\Miktex2\tex/latex/amsmath\amsopn.sty
Package: amsopn 2016/03/08 v2.02 operator names
)
\inf@bad=\count195
LaTeX Info: Redefining \frac on input line 234.
\uproot@=\count196
\leftroot@=\count197
LaTeX Info: Redefining \overline on input line 399.
\classnum@=\count198
\DOTSCASE@=\count199
LaTeX Info: Redefining \ldots on input line 496.
LaTeX Info: Redefining \dots on input line 499.
LaTeX Info: Redefining \cdots on input line 620.
\Mathstrutbox@=\box48
\strutbox@=\box49
\big@size=\dimen143
LaTeX Font Info:    Redeclaring font encoding OML on input line 743.
LaTeX Font Info:    Redeclaring font encoding OMS on input line 744.
\macc@depth=\count266
\c@MaxMatrixCols=\count267
\dotsspace@=\muskip16
\c@parentequation=\count268
\dspbrk@lvl=\count269
\tag@help=\toks21
\row@=\count270
\column@=\count271
\maxfields@=\count272
\andhelp@=\toks22
\eqnshift@=\dimen144
\alignsep@=\dimen145
\tagshift@=\dimen146
\tagwidth@=\dimen147
\totwidth@=\dimen148
\lineht@=\dimen149
\@envbody=\toks23
\multlinegap=\skip50
\multlinetaggap=\skip51
\mathdisplay@stack=\toks24
LaTeX Info: Redefining \[ on input line 2923.
LaTeX Info: Redefining \] on input line 2924.
) (F:\ProgramData\Miktex2\tex/latex/amsfonts\amssymb.sty
Package: amssymb 2013/01/14 v3.01 AMS font symbols
(F:\ProgramData\Miktex2\tex/latex/amsfonts\amsfonts.sty
Package: amsfonts 2013/01/14 v3.01 Basic AMSFonts support
\symAMSa=\mathgroup4
\symAMSb=\mathgroup5
LaTeX Font Info:    Redeclaring math symbol \hbar on input line 98.
LaTeX Font Info:    Overwriting math alphabet `\mathfrak' in version `bold'
(Font)                  U/euf/m/n --> U/euf/b/n on input line 106.
)) (F:\ProgramData\Miktex2\tex/latex/doublestroke\dsfont.sty
Package: dsfont 1995/08/01 v0.1 Double stroke roman fonts
) (F:\ProgramData\Miktex2\tex/latex/setspace\setspace.sty
Package: setspace 2011/12/19 v6.7a set line spacing
) (F:\ProgramData\Miktex2\tex/latex/tipa\tipa.sty
Package: tipa 2002/08/08 TIPA version 1.1
(F:\ProgramData\Miktex2\tex/latex/base\fontenc.sty
Package: fontenc 2020/08/10 v2.0s Standard LaTeX package
(F:\ProgramData\Miktex2\tex/latex/tipa\t3enc.def
File: t3enc.def 2001/12/31 T3 encoding
Now handling font encoding T3 ...
... no UTF-8 mapping file for font encoding T3
LaTeX Font Info:    Trying to load font information for T1+lmss on input line 3
57.
(F:\ProgramData\Miktex2\tex/latex/lm\t1lmss.fd
File: t1lmss.fd 2009/10/30 v1.6 Font defs for Latin Modern
))
LaTeX Font Info:    Trying to load font information for T1+lmr on input line 11
2.
(F:\ProgramData\Miktex2\tex/latex/lm\t1lmr.fd
File: t1lmr.fd 2009/10/30 v1.6 Font defs for Latin Modern
))) (F:\ProgramData\Miktex2\tex/latex/relsize\relsize.sty
Package: relsize 2013/03/29 ver 4.1
) (F:\ProgramData\Miktex2\tex/latex/base\textcomp.sty
Package: textcomp 2020/02/02 v2.0n Standard LaTeX package
) (F:\ProgramData\Miktex2\tex/latex/jknappen\mathrsfs.sty
Package: mathrsfs 1996/01/01 Math RSFS package v1.0 (jk)
\symrsfs=\mathgroup6
) (F:\ProgramData\Miktex2\tex/latex/fundus-calligra\calligra.sty
Package: calligra 2012/04/10 v1.9 LaTeX package calligra
) (F:\ProgramData\Miktex2\tex/latex/wasysym\wasysym.sty
Package: wasysym 2020/01/19 v2.4 Wasy-2 symbol support package
\symwasy=\mathgroup7
LaTeX Font Info:    Overwriting symbol font `wasy' in version `bold'
(Font)                  U/wasy/m/n --> U/wasy/b/n on input line 93.
) (F:\ProgramData\Miktex2\tex/latex/ragged2e\ragged2e.sty
Package: ragged2e 2021/02/05 v3.0 ragged2e Package
(F:\ProgramData\Miktex2\tex/latex/everysel\everysel.sty
Package: everysel 2021/01/20 v2.1 EverySelectfont Package (MS)
(F:\ProgramData\Miktex2\tex/latex/everysel\everysel-2011-10-28.sty))
\CenteringLeftskip=\skip52
\RaggedLeftLeftskip=\skip53
\RaggedRightLeftskip=\skip54
\CenteringRightskip=\skip55
\RaggedLeftRightskip=\skip56
\RaggedRightRightskip=\skip57
\CenteringParfillskip=\skip58
\RaggedLeftParfillskip=\skip59
\RaggedRightParfillskip=\skip60
\JustifyingParfillskip=\skip61
\CenteringParindent=\skip62
\RaggedLeftParindent=\skip63
\RaggedRightParindent=\skip64
\JustifyingParindent=\skip65
) (F:\ProgramData\Miktex2\tex/latex/physics\physics.sty
Package: physics 
(F:\ProgramData\Miktex2\tex/latex/l3packages/xparse\xparse.sty (F:\ProgramData\
Miktex2\tex/latex/l3kernel\expl3.sty
Package: expl3 2021-05-27 L3 programming layer (loader) 
(F:\ProgramData\Miktex2\tex/latex/l3backend\l3backend-dvips.def
File: l3backend-dvips.def 2021-05-07 L3 backend support: dvips
\l__pdf_internal_box=\box50
\g__pdf_backend_object_int=\count273
\l__pdf_backend_content_box=\box51
\l__pdf_backend_model_box=\box52
\g__pdf_backend_annotation_int=\count274
\g__pdf_backend_link_int=\count275
\g__pdf_backend_link_sf_int=\count276
)) (F:\ProgramData\Miktex2\tex/latex/l3packages/xparse\xparse-2020-10-01.sty (F
:\ProgramData\Miktex2\tex/latex/l3packages/xparse\xparse-generic.tex)))) (F:\Pr
ogramData\Miktex2\tex/latex/xcolor\xcolor.sty
Package: xcolor 2016/05/11 v2.12 LaTeX color extensions (UK)
(F:\ProgramData\Miktex2\tex/latex/graphics-cfg\color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: dvips.def on input line 225.
(F:\ProgramData\Miktex2\tex/latex/graphics-def\dvips.def
File: dvips.def 2017/06/20 v3.1d Graphics/color driver for dvips
)
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.
Package xcolor Info: Model `RGB' extended on input line 1364.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1366.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1367.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1368.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1370.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1371.
) (F:\ProgramData\Miktex2\tex/latex/microtype\microtype.sty
Package: microtype 2021/03/14 v2.8c Micro-typographical refinements (RS)
\MT@toks=\toks25
\MT@count=\count277
LaTeX Info: Redefining \textls on input line 790.
\MT@outer@kern=\dimen150
LaTeX Info: Redefining \textmicrotypecontext on input line 1374.
\MT@listname@count=\count278
(F:\ProgramData\Miktex2\tex/latex/microtype\microtype-pdftex.def
File: microtype-pdftex.def 2021/03/14 v2.8c Definitions specific to pdftex (RS)

LaTeX Info: Redefining \lsstyle on input line 915.
LaTeX Info: Redefining \lslig on input line 915.
\MT@outer@space=\skip66
)
Package microtype Info: Loading configuration file microtype.cfg.
(F:\ProgramData\Miktex2\tex/latex/microtype\microtype.cfg
File: microtype.cfg 2021/03/14 v2.8c microtype main configuration file (RS)
))
No file d4d6a6fd809d8da4.aux.
\openout1 = `d4d6a6fd809d8da4.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 24.
LaTeX Font Info:    ... okay on input line 24.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 24.
LaTeX Font Info:    ... okay on input line 24.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 24.
LaTeX Font Info:    ... okay on input line 24.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 24.
LaTeX Font Info:    ... okay on input line 24.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 24.
LaTeX Font Info:    ... okay on input line 24.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 24.
LaTeX Font Info:    ... okay on input line 24.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 24.
LaTeX Font Info:    ... okay on input line 24.
LaTeX Font Info:    Checking defaults for T3/cmr/m/n on input line 24.
LaTeX Font Info:    Trying to load font information for T3+cmr on input line 24
.
(F:\ProgramData\Miktex2\tex/latex/tipa\t3cmr.fd
File: t3cmr.fd 2001/12/31 TIPA font definitions
)
LaTeX Font Info:    ... okay on input line 24.
Preview: Fontsize 10pt
ABD: EverySelectfont initializing macros
LaTeX Info: Redefining \selectfont on input line 24.
LaTeX Info: Redefining \microtypecontext on input line 24.
Package microtype Info: Generating DVI output.
Package microtype Info: Character protrusion enabled (level 2).
Package microtype Info: Using default protrusion set `alltext'.
Package microtype Info: No font expansion.
Package microtype Info: No adjustment of tracking.
Package microtype Info: No adjustment of interword spacing.
Package microtype Info: No adjustment of character kerning.
(F:\ProgramData\Miktex2\tex/latex/microtype\mt-cmr.cfg
File: mt-cmr.cfg 2013/05/19 v2.2 microtype config. file: Computer Modern Roman 
(RS)
)
LaTeX Font Info:    Trying to load font information for OT1+lmr on input line 2
6.
(F:\ProgramData\Miktex2\tex/latex/lm\ot1lmr.fd
File: ot1lmr.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    Trying to load font information for OML+lmm on input line 2
6.
(F:\ProgramData\Miktex2\tex/latex/lm\omllmm.fd
File: omllmm.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    Trying to load font information for OMS+lmsy on input line 
26.
(F:\ProgramData\Miktex2\tex/latex/lm\omslmsy.fd
File: omslmsy.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    Trying to load font information for OMX+lmex on input line 
26.
(F:\ProgramData\Miktex2\tex/latex/lm\omxlmex.fd
File: omxlmex.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <10> on input line 26.
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <7> on input line 26.
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <5> on input line 26.
LaTeX Font Info:    Trying to load font information for U+msa on input line 26.

(F:\ProgramData\Miktex2\tex/latex/amsfonts\umsa.fd
File: umsa.fd 2013/01/14 v3.01 AMS symbols A
) (F:\ProgramData\Miktex2\tex/latex/microtype\mt-msa.cfg
File: mt-msa.cfg 2006/02/04 v1.1 microtype config. file: AMS symbols (a) (RS)
)
LaTeX Font Info:    Trying to load font information for U+msb on input line 26.

(F:\ProgramData\Miktex2\tex/latex/amsfonts\umsb.fd
File: umsb.fd 2013/01/14 v3.01 AMS symbols B
) (F:\ProgramData\Miktex2\tex/latex/microtype\mt-msb.cfg
File: mt-msb.cfg 2005/06/01 v1.0 microtype config. file: AMS symbols (b) (RS)
)
LaTeX Font Info:    Trying to load font information for U+rsfs on input line 26
.
(F:\ProgramData\Miktex2\tex/latex/jknappen\ursfs.fd
File: ursfs.fd 1998/03/24 rsfs font definition file (jk)
)
LaTeX Font Info:    Trying to load font information for U+wasy on input line 26
.
(F:\ProgramData\Miktex2\tex/latex/wasysym\uwasy.fd
File: uwasy.fd 2020/01/19 v2.4 Wasy-2 symbol font definitions
)

! LaTeX Error: Environment circuitikz undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.38 \end{align*}
                  
Here is how much of TeX's memory you used:
 7497 strings out of 479082
 108953 string characters out of 2863034
 447456 words of memory out of 3000000
 25034 multiletter control sequences out of 15000+600000
 425641 words of font info for 55 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 70i,8n,81p,354b,233s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.

**Comment by behackl** [comment]
> ! LaTeX Error: Environment circuitikz undefined.

This line says that you aren't loading the circuitikz package -- but we didn't change anything about the tex templates, and circuitikz was never automatically included in our default template as far as I can tell. Are you sure you are testing with the same code that you were using with `v0.6.0`?

**Comment by Ribisl** [comment]
yes I'm pretty sure, I added it in the v0.6 and there it worked!

**Comment by behackl** [comment]
Can you share the code that you were using?

**Comment by Ribisl** [comment]
[aufgabe1.zip](https://github.com/ManimCommunity/manim/files/6586871/aufgabe1.zip)

**Comment by Ribisl** [comment]
I reinstalled everything again and it seems, that in the tex_template.py circuitikz  was missing

**Comment by behackl** [comment]
You must have changed the file before as well, I otherwise don't have an explanation for why it would have worked before.

FYI: you can both configure a different tex template file for Manim to use instead of the one in the library folder, as well as piece together a suitable `TexTemplate` (look for the class in our documentation) to pass to `MathTex`.

Given that this seems to be resolved now, I'll close the issue (feel free to keep commenting if you see this otherwise!)

**Comment by 0xCoto** [comment]
Hi @Ribisl - Have you managed to install Circuitikz on v0.9.0 as well? I'm facing problems after updating, but I tried the `mathrsfs` package example [here](https://docs.manim.community/en/stable/tutorials/using_text.html#extra-latex-packages) and it worked fine. So it seems to be a package-specific issue, not quite sure...

(Looks like we're both working on similar RF engineering topics by the way haha!)
