### PR TITLE
Added :class:`~.PolarPlane`, a subclass of :class:`~.NumberPlane` for polar coordinates.

### PR DESCRIPTION
**Pull request by ralphieraccoon**
## Motivation
To create a version of `NumberPlane` for polar coordinates with a set of useful (and not so useful) default unit labels.

## Explanation for Changes
Adds a subclass of `NumberPlane` for polar coordinates. Four default sets of azimuth labels are provided (number of ticks customizable using `azimuth_line_frequency`, though convenient defaults are provided):

- `"PI radians"`: Fractional labels in the interval `[0, 2π]` with `π` as a constant.
- `"TAU radians"`: Fractional labels in the interval `[0, τ]` with `τ` as a constant.
- `"degrees"`: Decimal labels in the interval `[0, 360]` with a degree symbol.
- `"gradians"`: Decimal labels in the interval `[0, 400]` with a superscript "g".

### Examples
PolarPlaneDegrees-1
PolarPlaneGradians-1
PolarPlanePIradians-1
PolarPlaneTAUradians-1

## Testing Status
Have generated planes with each set of default `azimuth_units`, as can be seen above.

## Further Comments
Will look at adding a special transformation animation between a `NumberPlane` and `PolarPlane` in future (a naive implementation with `apply_function` looks "weird", see #1264).

## Checklist
- [x] I have read the [Contributing Guidelines](https://docs.manim.community/en/latest/contributing.html)
- [x] I have written a descriptive PR title (see top of PR template for examples)
- [x] I have written a changelog entry for the PR or deem it unnecessary
- [x] My new functions/classes either have a docstring or are private
- [x] My new functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [x] My new documentation builds, looks correctly formatted, and adds no additional build warnings

## Reviewer Checklist
- [x] The PR title is descriptive enough
- [x] The PR is labeled correctly
- [ ] The changelog entry is completed if necessary
- [ ] Newly added functions/classes either have a docstring or are private
- [ ] Newly added functions/classes have [tests](https://github.com/ManimCommunity/manim/wiki/Testing) added and (optional) examples in the docs
- [ ] Newly added documentation builds, looks correctly formatted, and adds no additional build warnings

### CODE REVIEW

File: manim/mobject/coordinate_systems.py [hunk 1]
```diff
@@ -495,3 +503,321 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+
+    radius_line_frequency : :class:`float`, optional
+        The frequency of faded lines in the radius.
+
+    azimuth_units : Optional[:class:`str`], optional
+        Specifies a default labelling system for the azimuth. Choices are:
+
+            - ``"PI radians"``: Fractional labels in the interval :math:`\\left[0, 2\\pi\\right]` with :math:`\\pi` as a constant.
+
+              .. manim:: PolarPlanePIradians
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:531]: I think it would be less disruptive for the documentation if there was one rendered example illustrating all four choices for `azimuth_units`.

File: manim/mobject/coordinate_systems.py [hunk 2]
```diff
@@ -495,3 +503,321 @@ def get_coordinate_labels(self, *numbers, **kwargs):
     def add_coordinates(self, *numbers):
         self.add(self.get_coordinate_labels(*numbers))
         return self
+
+
+class PolarPlane(NumberPlane):
+    """A version of `NumberPlane` for polar coordinates.
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:509]: If the docstring were a raw string (`r"""`), the backslashes in it would not have to be escaped. I would prefer that (but won't block the PR over it).

File: manim/mobject/coordinate_systems.py [hunk 3]
```diff
@@ -495,3 +503,321 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+                    class PolarPlaneGradians(Scene):
+                        def construct(self):
+                            self.add(polarplot)
+
+    azimuth_offset : Optional[:class:`float`], optional
+        The angle offset of the azimuth labels, expressed in radians. If ``None`` is specified then it will
+        use the default specified by ``azimuth_units``.
+
+            - ``"PI radians"`` or ``"TAU radians"`` or ``None``: :math:`0`
+            - ``"degrees"`` or ``"gradians"``: :math:`\\frac{\\pi}{2}`
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:586]: I feel that this is a pretty weird inconsistency and would actually prefer if the default offset was 0 in all cases.

File: manim/mobject/coordinate_systems.py [hunk 4]
```diff
@@ -495,3 +503,321 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+    azimuth_direction : Optional[:class:`str`], optional
+        The direction of the azimuth labels.
+
+            - ``"CW"``: Clockwise.
+            - ``"CCW"`` Anti-clockwise.
+
+        If ``None`` is specified then it will use the default specified by ``azimuth_units``:
+
+            - `"PI radians"` or ``"TAU radians"`` or ``None``: ``"CW"``
+            - `"degrees"` or `"gradians"`: ``"CCW"``
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:597]: Again, I feel this inconsistency is somewhat artificial. By default, the direction should be mathematically positive, i.e., counterclockwise.

File: manim/mobject/coordinate_systems.py [hunk 5]
```diff
@@ -495,3 +503,321 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+            The coordinate azimuth (:math:`\\theta`).
+
+        Returns
+        -------
+        :class:`numpy.ndarray`
+            The point.
+        """
+        return self.coords_to_point(radius * np.cos(azimuth), radius * np.sin(azimuth))
+
+    def pr2pt(self, radius, azimuth):
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:698]: Personal opinion: I think these abbreviated methods are mainly confusing (although it's certainly not as extreme as with `Text` here) and they should not be added. Further opinions are welcome.

File: manim/mobject/coordinate_systems.py [hunk 6]
```diff
@@ -495,3 +503,321 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+
+        Returns
+        -------
+        Tuple[:class:`float`, :class:`float`]
+            The coordinate radius (:math:`r`) and the coordinate azimuth (:math:`\\theta`).
+        """
+        x, y = self.point_to_coords(point)
+        return np.sqrt(x ** 2 + y ** 2), np.arctan2(y, x)
+
+    def pt2pr(self, point):
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:718]: See above.

File: manim/mobject/coordinate_systems.py [hunk 7]
```diff
@@ -495,3 +503,321 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+        if a_vals is None:
+            a_vals = np.arange(0, 1, self.azimuth_frequency)
+        r_mobs = self.get_x_axis().get_number_mobjects(*r_vals)
+        if self.azimuth_direction == "CCW":
+            d = 1
+        elif self.azimuth_direction == "CW":
+            d = -1
+        else:
+            d = 0
+            ValueError()
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:736]: ?

**Review by behackl — CHANGES_REQUESTED** [review]
Thank you for your contribution, and sorry that it took so long for someone to review your proposal!

In general, I like the idea of adding a `PolarPlane`; and I don't really have many suggestions / points for discussion.

Should `PolarPlane` actually inherit from `NumberPlane`? Wouldn't it be semantically cleaner to have it inherit from `CoordinateSystem`?

File: manim/mobject/coordinate_systems.py (hunk 3 above)
Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:586]: This is based on the convention of 0 degrees and gradians being oriented to "north" which is of course typically the vertical axis on most planar projections (maps etc.).

File: manim/mobject/coordinate_systems.py (hunk 5 above)
Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:698]: This is based on the template of the existing class `ComplexPlane` which includes abbreviated methods like this. Are they planned to be removed?

File: manim/mobject/coordinate_systems.py (hunk 3 above)
Comment (behackl) [reply manim/mobject/coordinate_systems.py:586]: https://en.m.wikipedia.org/wiki/Polar_coordinate_system says that this is mainly true for navigation, but not in general mathematics. (Also searching the web for polar planes in degrees yields most results with the orientation to the right.)

**Comment by ralphieraccoon** [comment]
That's no problem. Regarding the issue of inheritance, this was discussed in the relevant issue #1264 and @MrMallIronmaker suggested it should inherit from `NumberPlane`. Personally I can see advantages and disadvantages for both, so I'd like to get a consensus before making changes regarding that, so someone else doesn't ask me to change it back.

(P.S. is it possible for you to link #1264 to this PR? I forgot to do it when creating it and I can't seem to do it now. Thanks!)

File: manim/mobject/coordinate_systems.py (hunk 3 above)
Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:586]: Fair enough, manim is primarily a mathematics package so I understand your point and will change the default. It's obviously easily changed if someone needs to use it for illustrating navigational data.

**Comment by behackl** [comment]
> Regarding the issue of inheritance

Sure, we should agree on the way forward. To make my argument a bit more explicit: I think that `NumberPlane` refers to a two-dimensional cartesian coordinate system, while `CoordinateSystem` refers to a general one. For me, the polar plane is a specialized coordinate system, but not a specialized cartesian 2D one. Also, you don't really seem to use any `NumberPlane` specific features, or do you?

File: manim/mobject/coordinate_systems.py (hunk 4 above)
Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:597]: I assume this is the same sentiment from the previous comment, so I'll make the change. Also, it appears I have made a docstring typo, radians should of course be CCW (not that it matters anymore since they will all be now).

File: manim/mobject/coordinate_systems.py (hunk 7 above)
Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:736]: The `ValueError()` is there to catch any string other than "CW" or "CCW". I'll be the first to admit I'm not well versed in pythonic conventions, so it's very possible there's a more correct way of doing this.

**Comment by jsonvillanueva** [comment]
To add to this discussion of general inheritance/design decision (I haven't looked at the code for PolarPlane btw), I think PolarPlane/PolarCoordinateSystem/etc. and what is currently NumberPlane (which should probably be renamed/deprecated/or an alias of CartesianPlane/CartesianCoordinateSystem/etc.) should inherit from EuclideanPlane/EuclideanCoordinateSystem/etc. as that's axiomatically how I see them inheriting from the more general "Plane". Perhaps CoordinateSystem should be the general "Plane"?

**Comment by ralphieraccoon** [comment]
The class is currently constructed by creating a `NumberPlane` with `super()` (much like in `ComplexPlane`) and then applying a function to it to turn cartesian coordinates into polar. Of course it would be possible to write the functions in `NumberPlane` to create a radial grid instead of a square one, it would just take more lines of code. But, on the other hand, I think it would require less computation and would probably be more extensible in future I imagine.

**Comment by jsonvillanueva** [comment]
> I think it would require less computation and would probably be more extensible in future I imagine.

I think this is worth discussion and if should likely be brought up in the `Manim Architecture` Town Hall meeting coming up. There's a couple of other impactful design decisions that I believe should be altered as well where the inheritance doesn't really match up with what is mathematically expected (e.g. Circle inheriting from Ellipse -- where mathematically it makes more sense that Circle IS-A special type of Ellipse).

I'm ultimately in favor of what makes Manim more extensible/intuitive; but seeing as this is a really useful feature, I can be onboard with this integrating this and then later handling inheritance/redesign.

**Comment by ralphieraccoon** [comment]
> (e.g. Ellipse inheriting from Circle -- where mathematically it makes more sense that Circle IS-A special type of Ellipse)

Apparently that specific example is a well known problem in software development: [Circle–ellipse problem](https://en.wikipedia.org/wiki/Circle%E2%80%93ellipse_problem)

File: manim/mobject/coordinate_systems.py [hunk 8]
```diff
@@ -495,3 +503,279 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+        if azimuth_units in [
+            "PI radians",
+            "TAU radians",
+            "degrees",
+            "gradians",
+            None,
+        ]:
+            self.azimuth_units = azimuth_units
+        else:
+            ValueError(
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:598]: If you want to throw an error, you have to `raise` it.

```suggestion
            raise ValueError(
```

File: manim/mobject/coordinate_systems.py [hunk 9]
```diff
@@ -495,3 +503,279 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+
+        Returns
+        -------
+        :class:`numpy.ndarray`
+            The point.
+        """
+        return self.coords_to_point(radius * np.cos(azimuth), radius * np.sin(azimuth))
+
+    def pr2pt(self, radius, azimuth):
+        """Abbreviation for `polar_to_point`"""
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:657]:
```suggestion
        """Abbreviation for ``polar_to_point``"""
```

File: manim/mobject/coordinate_systems.py [hunk 10]
```diff
@@ -495,3 +503,279 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+        Returns
+        -------
+        Tuple[:class:`float`, :class:`float`]
+            The coordinate radius (:math:`r`) and the coordinate azimuth (:math:`\theta`).
+        """
+        x, y = self.point_to_coords(point)
+        return np.sqrt(x ** 2 + y ** 2), np.arctan2(y, x)
+
+    def pt2pr(self, point):
+        """Abbreviation for `point_to_polar`"""
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:677]:
```suggestion
        """Abbreviation for ``point_to_polar``"""
```

File: manim/mobject/coordinate_systems.py [hunk 11]
```diff
@@ -495,3 +503,279 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+
+
+    azimuth_offset : :class:`float`, optional
+        The angle offset of the azimuth labels, expressed in radians.
+
+    azimuth_direction : :class:`str`, optional
+        The direction of the azimuth labels.
+
+            - ``"CW"``: Clockwise.
+            - ``"CCW"``: Anti-clockwise.
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:564]: In the rendered documentation this list looks like as if it was indented by one level too much; it appears within a blockquote.

```suggestion
        - ``"CW"``: Clockwise.
        - ``"CCW"``: Anti-clockwise.
```

**Review by behackl — APPROVED** [review]
Looks good to me, thank you very much for your efforts! I think we can move this along; I only have a few further suggestions for improvement of the documentation. Feel free to have a look; if I don't hear back I'll apply them in a few hours to get this PR merged before the next release.

**Comment by hydrobeam** [comment]
The way variables are set using `x_min`, `x_max` and `x_line_frequency` doesn't follow the precedent set by #1161. Would it be possible to switch to using `x_range` and `y_range` as is the case for the other classes in `CoordinateSystem` for that PR?

**Comment by ralphieraccoon** [comment]
> The way variables are set using `x_min`, `x_max` / `y_min,` `y_max` and `x_line_frequency`, `y_line_frequency` in `super.__init__()` would be broken by #1161. Would it be possible to switch to using `x_range` and `y_range` as is the case for the other classes in `CoordinateSystem` for that PR?

I can do this, but probably not in time for 0.6.0. If you like I can PR your branch with the needed changes.

File: manim/mobject/coordinate_systems.py [hunk 12]
```diff
@@ -731,3 +739,298 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+        return np.sqrt(x ** 2 + y ** 2), np.arctan2(y, x)
+
+    def pt2pr(self, point):
+        """Abbreviation for ``point_to_polar``"""
+        return self.point_to_polar(point)
+
+    def get_coordinate_labels(self, r_vals, a_vals, **kwargs):
+        if r_vals is None:
+            r_vals = [
+                r for r in self.get_x_axis().default_numbers_to_display() if r >= 0
```
Comment (behackl) [inline manim/mobject/coordinate_systems.py:918]: This will have to be adapted, the current documentation build fails (https://readthedocs.org/api/v2/build/13651256.txt) with:

```
  File "<string>", line 9, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/manimce/envs/1325/lib/python3.8/site-packages/manim/mobject/coordinate_systems.py", line 1009, in add_coordinates
    self.add(self.get_coordinate_labels(r_vals, a_vals))
  File "/home/docs/checkouts/readthedocs.org/user_builds/manimce/envs/1325/lib/python3.8/site-packages/manim/mobject/coordinate_systems.py", line 918, in get_coordinate_labels
    r for r in self.get_x_axis().default_numbers_to_display() if r >= 0
  File "/home/docs/checkouts/readthedocs.org/user_builds/manimce/envs/1325/lib/python3.8/site-packages/manim/mobject/mobject.py", line 530, in __getattr__
    raise AttributeError(f"{type(self).__name__} object has no attribute '{attr}'")
AttributeError: NumberLine object has no attribute 'default_numbers_to_display'
```

**Comment by hydrobeam** [comment]
I'm working on fixing the inconsistencies/changes caused by #1161 in this PR. I'll share the changes as soon as I'm done.

File: manim/mobject/coordinate_systems.py (hunk 12 above)
Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:918]: Some of the function names have changed since the upstream merge. I've fixed that problem by changing it to `get_tick_range()`, but I'm getting an error out of `get_number_mobjects()` it seems `VGroup` won't allow `DecimalNumber`:

```
TypeError: All submobjects must be of type VMobject
```

Is this a bug?

Comment (hydrobeam) [reply manim/mobject/coordinate_systems.py:918]: Try replacing `get_number_mobjects` with `add_numbers`, that's how I got it to work on my end.

Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:918]: Yeah, that seems to work, still got a some strange rendering errors on my end though. Anyway, I'm on BST so I'll be off to bed soon. Thanks for your help @hydrobeam, once you get it working with #1161 you could start a PR on my branch and I could merge it tomorrow morning, would that be best?

Comment (hydrobeam) [reply manim/mobject/coordinate_systems.py:918]: Sure sounds good! I'm also encountering some weird errors and I suspect it has to do with the code for  `NumberPlane` itself. I'll try to isolate the error.

Comment (behackl) [reply manim/mobject/coordinate_systems.py:918]: Any updates here?

Comment (hydrobeam) [reply manim/mobject/coordinate_systems.py:918]: The issue turned out to be the new way `NumberPlane` was drawn (the box look). It intrduces odd errors where lines are off significant if the numbers aren't right. This was a bit unforseen, so I suggest we revert to the previous method of drawing `NumberPlane`

Also, since labels are added based on range, this means that there's a bit of an overflow in the x_direction of coordinate labels, especially for degrees (360 labels). We can either remove the label messages, or reintroduce `x_line_frequency`. I'm in favour of the first option.

Comment (behackl) [reply manim/mobject/coordinate_systems.py:918]: > The issue turned out to be the new way `NumberPlane` was drawn (the box look). It intrduces odd errors where lines are off significant if the numbers aren't right. This was a bit unforseen, so I suggest we revert to the previous method of drawing `NumberPlane`
> 

Sounds good to me. Could you take care of it (ideally within the next few hours)? We could bundle these changes to the PR I just opened, #1430.

> Also, since labels are added based on range, this means that there's a bit of an overflow in the x_direction of coordinate labels, especially for degrees (360 labels). We can either remove the labels along the radius, or reintroduce `x_line_frequency`. I'm in favour of the first option.

I'm not sure I understand. I would like to have the labels around the outer circle; for 360 degrees not every degree should be labeled.

Comment (hydrobeam) [reply manim/mobject/coordinate_systems.py:918]: > Sounds good to me. Could you take care of it (ideally within the next few hours)? We could bundle these changes to the PR I just opened, #1430.

👍

> I'm not sure I understand. I would like to have the labels around the outer circle; for 360 degrees not every degree should be labeled.

My bad! I meant the labels across the radius in the inner circle that travel horizontally. The outer labels look as expected under the new change/

File: manim/mobject/coordinate_systems.py [hunk 13]
```diff
@@ -731,3 +739,298 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+            color=color,
+            x_line_frequency=self.azimuth_frequency * TAU,
+            y_line_frequency=radius_line_frequency,
+            x_axis_config=radius_config,
+            x_min=None if (radius_max is None) else -radius_max,
+            x_max=radius_max,
+            y_min=-config["frame_x_radius"] if (radius_max is None) else -radius_max,
+            y_max=config["frame_x_radius"] if (radius_max is None) else radius_max,
+            **kwargs,
+        )
```
Comment (hydrobeam) [inline manim/mobject/coordinate_systems.py:856]:
```suggestion

        x_min = (-config["frame_x_radius"] if (radius_max is None) else -radius_max)
        x_max = (config["frame_x_radius"] if (radius_max is None) else radius_max)
        x_line_frequency = (self.azimuth_frequency * TAU)

        y_min = (-config["frame_y_radius"] if (radius_max is None) else -radius_max)
        y_max = (config["frame_y_radius"] if (radius_max is None) else radius_max)
        y_line_frequency = radius_line_frequency

        super().__init__(
            x_range=(x_min, x_max, x_line_frequency),
            y_range=(y_min, y_max, y_line_frequency),
            x_axis_config=radius_config,
            color=color,
            **kwargs,
        )

File: manim/mobject/coordinate_systems.py [hunk 14]
```diff
@@ -731,3 +739,303 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+        return self.point_to_polar(point)
+
+    def get_coordinate_labels(self, r_vals, a_vals, **kwargs):
+        if r_vals is None:
+            r_vals = [
+                r for r in self.get_x_axis().default_numbers_to_display() if r >= 0
+            ]
+        if a_vals is None:
+            a_vals = np.arange(0, 1, self.azimuth_frequency)
+        r_mobs = self.get_x_axis().get_number_mobjects(*r_vals)
```
Comment (hydrobeam) [inline manim/mobject/coordinate_systems.py:927]:
```suggestion
    def get_coordinate_labels(self, r_vals, a_vals, **kwargs):
        if r_vals is None:
            r_vals = [r for r in self.get_x_axis().get_tick_range() if r >= 0]
        if a_vals is None:
            a_vals = np.arange(0, 1, self.azimuth_frequency)
        r_mobs = self.get_x_axis().add_numbers(r_vals)
```

File: manim/mobject/coordinate_systems.py (hunk 13 above)
Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py]: Thanks! I can look at refactoring it to work without deprecated code for the next release. I've been told the whole inheritance  tree for `coordinate_systems` might be rewritten in the near future anyway, so it might be best to wait for that to happen and change things then.

File: manim/mobject/coordinate_systems.py (hunk 14 above)
Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:927]: I think this is something `black` does, so `pre-commit.ci` might just revert it.

Comment (hydrobeam) [reply manim/mobject/coordinate_systems.py:927]: There is also a difference in `get_tick_range()` and `.add_numbers()`  (which is why the docs are currently failing).

Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py:927]: Oh, sorry, didn't notice that. Was commenting on the expanded square brackets.

Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py]: image
 Still broken unfortunately.

Comment (hydrobeam) [reply manim/mobject/coordinate_systems.py]: It should be fixed with #1430, where `NumberPlane` is restored to the previous usage. I've tested it locally with the changes and it works as expected.

Comment (ralphieraccoon) [reply manim/mobject/coordinate_systems.py]: OK. I've been looking at adding `x_border`, `y_border` arguments to `NumberPlane` which can be used to fix some of the visual issues with `PolarPlane` namely not drawing the border gridline on one of the axes.

File: manim/mobject/coordinate_systems.py [hunk 15]
```diff
@@ -731,3 +739,301 @@ def get_coordinate_labels(self, *numbers, **kwargs):
...
+            if azimuth_line_frequency is None
+            else azimuth_line_frequency
+        )
+
+        x_min = -config["frame_x_radius"] if (radius_max is None) else -radius_max
+        x_max = config["frame_x_radius"] if (radius_max is None) else radius_max
+        x_line_frequency = self.azimuth_frequency * TAU
+
+        y_min = -config["frame_y_radius"] if (radius_max is None) else -radius_max
+        y_max = config["frame_y_radius"] if (radius_max is None) else radius_max
```
Comment (hydrobeam) [inline manim/mobject/coordinate_systems.py:852]: On review, this yields intended results with the axes. 
```suggestion
        y_min = -config["frame_x_radius"] if (radius_max is None) else -radius_max
        y_max = config["frame_x_radius"] if (radius_max is None) else radius_max
```

**Comment by hydrobeam** [comment]
From one of the examples in the doctest (after the changes in #1430):
image

The coordinates along the azimuth are a little bit unusual since they're created based on the range of the Plane (which is very small in these cases). If there isn't an easy way to correct them, maybe it would be worthwhile to simply remove the coordinates along the azimuth?

**Comment by ralphieraccoon** [comment]
> The coordinates along the azimuth are a little bit unusual since they're created based on the range of the Plane (which is very small in these cases). If there isn't an easy way to correct them, maybe it would be worthwhile to simply remove the coordinates along the azimuth?

For the sake of getting this merged for 0.6.0, I think it's probably the best option. I'm leaning towards a complete rewrite where things are built from scratch, rather than relying on `NumberPlane`. There's been some suggestions regarding this already. We can consider this a temporary solution.

**Review by hydrobeam — APPROVED** [review]

**Comment by hydrobeam** [comment]
I was doing some light testing and noticed that if the `radius_max` is just above a whole number, then it looks like a circle:
```py
class A(Scene):
    def construct(self):
        polarplot_pi = PolarPlane(azimuth_units="PI radians", radius_max=3 + 1e-8).add_coordinates()
        self.add(polarplot_pi)
```
image

Would we want to update the documentation to use this construction as opposed to scaling from a full size plane?

**Comment by ralphieraccoon** [comment]
image

Have you changed something else? I don't get the same result.

**Comment by hydrobeam** [comment]
> 
> 
> image
> 
> 
> 
> Have you changed something else? I don't get the same result.
> 
> 
> 
> 

#1430 has been merged so updating the branch should yield that plane.

**Comment by ralphieraccoon** [comment]
I wouldn't worry about the documentation too much, it will likely not work that way with v2.

**Comment by hydrobeam** [comment]
Could you submit an empty commit to restart the checking process? The macOS test randomly failed 🤔

**Comment by ralphieraccoon** [comment]
Looks like we missed 0.6.0. That's fine, I've started work on v2 already. It's on a new branch, so should I close this PR and start a new one?

**Comment by behackl** [comment]
> Looks like we missed 0.6.0. That's fine, I've started work on v2 already. It's on a new branch, so should I close this PR and start a new one?

Sorry - yes please. (The release was already a bit delayed due to other bugs that needed to be fixed first; I felt more comfortable with not merging this PR for the release (especially if there were plans to rework some of it anyways).

If you already have a separate branch, then the easiest approach is to open a new PR, yes. Thank you for your efforts!
