### ISSUE TITLE
AttributeError: 'ThreeDCamera' object has no attribute 'extract_mobject_family_members'

### ISSUE THREAD

**Issue by BrendanMartin** [ManimCommunity/manim#669]
Tried running the example:
```python
# To see the text in the traditional form:
class Text3D3(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes()
        self.set_camera_orientation(phi=75 * DEGREES,theta=-45*DEGREES)
        text3d=TextMobject("This is a 3D text")

        self.add_fixed_in_frame_mobjects(text3d) #<----- Add this
        text3d.to_corner(UL)

        self.add(axes)
        self.begin_ambient_camera_rotation()
        self.play(Write(text3d))

        sphere = ParametricSurface(
            lambda u, v: np.array([
                1.5*np.cos(u)*np.cos(v),
                1.5*np.cos(u)*np.sin(v),
                1.5*np.sin(u)
            ]),v_min=0,v_max=TAU,u_min=-PI/2,u_max=PI/2,checkerboard_colors=[RED_D, RED_E],
            resolution=(15, 32)).scale(2)

        self.play(LaggedStart(ShowCreation,sphere))
        self.wait(2)
```

And got the error:
```
Traceback (most recent call last):
  File "c:\users\brendan\appdata\local\programs\python\python38\lib\site-packages\manim\__main__.py", line 75, in main
    scene.render()
  File "c:\users\brendan\appdata\local\programs\python\python38\lib\site-packages\manim\scene\scene.py", line 88, in render
    self.construct()
  File "test.py", line 141, in construct
    self.add_fixed_in_frame_mobjects(text3d) #<----- Add this
  File "c:\users\brendan\appdata\local\programs\python\python38\lib\site-packages\manim\scene\three_d_scene.py", line 223, in add_fixed_in_frame_mobjects
    self.renderer.camera.add_fixed_in_frame_mobjects(*mobjects)
  File "c:\users\brendan\appdata\local\programs\python\python38\lib\site-packages\manim\camera\three_d_camera.py", line 370, in add_fixed_in_frame_mobjects
    for mobject in self.extract_mobject_family_members(mobjects):
AttributeError: 'ThreeDCamera' object has no attribute 'extract_mobject_family_members'
```

**System Specifications**

<details><summary>System Details</summary>

- OS: Windows 10
- Python version (`python/py/python3 --version`): 3.8

**Comment by leotrs** [comment]
Hi @BrendanMartin and thank you for reporting.

Could you please share a link to where you got this example from?

Also, are you on the latest version of manim CE?

**Comment by BrendanMartin** [comment]
@leotrs I found this example here: https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/6b_plots_3D/scenes.md

And yes, I'm on the latest version (0.1.0)

**Comment by leotrs** [comment]
Unfortunately, I believe @elteoremadebeethoven uses 3b1b manim.

**Comment by BrendanMartin** [comment]
I see. Do you know if there an equivalent in manimce?

**Comment by leotrs** [comment]
Unfortunately I don't. You can see some manim CE examples in 3D here: https://manimce.readthedocs.io/en/stable/examples/3d.html

I believe @kolibril13 has a bit more expertise in 3D stuff than I do.

**Comment by kolibril13** [comment]
Hi @BrendanMartin , this is a nice feature that was unfortunately broken with the pr #281, and I already made an issue for that:https://github.com/ManimCommunity/manim/issues/569
Therefore, I suggest we discuss this in 569 and close this issue.
Unfortunately, I don't know how to fix it right now, but feel free to have a look at it if you want to ;)

**Comment by kolibril13** [comment]
Closing, further discussion in #674
