### ISSUE TITLE
LaggedStartMap new bug (since 0.19.1)

### ISSUE THREAD

**Issue by wildmathing** [ManimCommunity/manim#4508]
## Description of bug / unexpected behavior
LaggedStartMap is producing an error now, but the same code works fine in 0.19.0. I guess it's releated to the refactoring of  LaggedStartMap in 0.19.1:  https://github.com/ManimCommunity/manim/pull/4214

## Expected behavior
All three scenes should be rendered, but in version 0.19.1 only one of the scenes works

## How to reproduce the issue
<details><summary>Code for reproducing the problem</summary>

```py
from manim import *


# Works fine
class TestLaggedStartMap(Scene):
    def construct(self):
        circles = VGroup(Circle() for _ in range(5)).arrange()
        self.play(LaggedStartMap(GrowFromCenter, circles, lag_ratio=0.3))
        self.wait()


# Breaks because of the formula(?)
class TestLaggedStartMap2(Scene):
    def construct(self):
        formula = MathTex("2026",  "=", "2", r"\times", "1013")
        self.play(LaggedStartMap(GrowFromCenter, formula, lag_ratio=0.3))
        self.wait()


# Breaks because of the scale_factor=2 (but it should be applied to the Indicate)
class TestLaggedStartMap3(Scene):
    def construct(self):
        circles = VGroup(Circle() for _ in range(5)).arrange()
        self.play(LaggedStartMap(Indicate, circles, scale_factor=2, lag_ratio=0.3))
        self.wait()
```

</details>

## Logs
<details><summary>Terminal output</summary>

Animation.__init__() got an unexpected keyword argument 'scale_factor'
GrowFromCenter.__init__() takes from 2 to 3 positional arguments but 5 were given   

</details>

## System specifications

<details><summary>System Details</summary>

- OS Windows 11
- Python version 3.12.1

</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution: TexLive 2023
+ Installed LaTeX packages: full installation
</details>

## Additional comments
https://discord.com/channels/581738731934056449/1019649969596153968/threads/1447988215142158558

**Comment by irvanalhaq9** [comment]
`ApplyMethod` actually works perfectly fine.
You should pass all arguments of the method as positional arguments because that's how `ApplyMethod` is designed to work. Any keyword arguments will not be forwarded to the method itself, but to the animation class.

FYI: even in the previous version, if you run that code, the keyword argument `buff=...` will not have any effect unless you pass it as a positional argument to `next_to`.
Example:
```
class TestApplyMethod(Scene):
    def construct(self):
        circle = Circle()
        self.play(ApplyMethod(circle.next_to, ORIGIN, UR, 0.2)) 
        self.wait()
```

The current version will tell you that the `buff=...` argument is unnecessary, and throw a TypeError, while in the previous one, it tells you nothing, and that might cause you not to know that it does not have any effect at all.

As for `LaggedStartMap`, there does seem to be an issue. From what I can see, `**kwargs` are forwarded both to `animation_class` and to `super().__init__`. Since they are already consumed by `animation_class`, passing them again to the parent class is unnecessary and that's the source of the issue.

**Comment by wildmathing** [comment]
> FYI: even in the previous version, if you run that code

Then we'll see, that it works fine. Did you tried? I I've checked v0.19.0 and v0.18.0 now: buff=2 kwarg was applied. I used ApplyMethod this way many times and only in v0.19.1 noticed a problem. But if it's the expected behavior, I'm totaly ok with that, just want to help. The docs states that **kwargs shoud be applied to the Transform, so you're right, maybe an unexpected behavior was in previous versions, but not now. Thank you for clearing the issue. Hope LaggedStartMap would be fixed

```py
class TestApplyMethod(Scene):
    def construct(self):
        circle = Circle()
        self.play(ApplyMethod(circle.next_to, ORIGIN, UR, buff=2))
        self.wait()
```

https://github.com/user-attachments/assets/14c87147-98d0-4a36-8c65-3ae202e83eea

**Comment by irvanalhaq9** [comment]
> Then we'll see, that it works fine. Did you tried? I I've checked v0.19.0 and v0.18.0 now: buff=2 kwarg was applied. I used ApplyMethod this way many times and only in v0.19.1 noticed a problem.

What I mean by "it doesn't have any effect in the previous version" is if you pass different values for the keyword argument `buff`, the result is just the same because it's the wrong way of passing arguments in `ApplyMethod`.

For example:
`self.play(ApplyMethod(circle.next_to, ORIGIN, UR, buff=2))`
or
`self.play(ApplyMethod(circle.next_to, ORIGIN, UR, buff=0.2))`
or
`self.play(ApplyMethod(circle.next_to, ORIGIN, UR, buff=20))`

All of them will give the same result because the `buff` was not forwarded to the method. But it does not tell you that, and just silently swallow the error.

The correct way is:
`self.play(ApplyMethod(circle.next_to, ORIGIN, UR, 2))`
or
`self.play(ApplyMethod(circle.next_to, ORIGIN, UR, 0.2))`
or
`self.play(ApplyMethod(circle.next_to, ORIGIN, UR, 20))`

Edit:
Also the correct way is:
`self.play(ApplyMethod(circle.next_to, ORIGIN, UR, {"buff": 2}))`

**Comment by irvanalhaq9** [comment]
https://github.com/user-attachments/assets/c10d1288-33d3-44d1-81fc-1016b59605f1

This is the result if the buff = 2

**Comment by irvanalhaq9** [comment]
For the current version, the codes:

self.play(ApplyMethod(circle.next_to, ORIGIN, UR, buff=2))
or
self.play(ApplyMethod(circle.next_to, ORIGIN, UR, buff=0.2))
or
self.play(ApplyMethod(circle.next_to, ORIGIN, UR, buff=20))

will all throw a TypeError.

**Comment by irvanalhaq9** [comment]
The correct way (and this is the way `ApplyMethod` was designed to work) is to pass all the arguments for `next_to` as positional arguments.
example:
self.play(ApplyMethod(circle.next_to, ORIGIN, UR, 2))

edit:
Also the correct way: add a dictionary at the end of positional arguments.
example:
self.play(ApplyMethod(circle.next_to, ORIGIN, UR, {"buff": 2}))

**Comment by wildmathing** [comment]
Yeah, I think you're right, thank you! There are no errors in v.0.18.0 and 0.19.0, but `buff=2` has no effect. Maybe I didn't noticed it when used. And now in 0.19.1 and 0.20.0 it's better to see the error to know that's smth is wrong. I've deleted this part of the issue now. So only LaggedStartMap should be fixed

**Comment by irvanalhaq9** [comment]
Glad that helped. Thanks for confirming!

**Comment by irvanalhaq9** [comment]
I opened a PR for this issue: #4613

```
class TestLaggedStartMap3(Scene):
    def construct(self):
        circles = VGroup(Circle() for _ in range(5)).arrange()
        self.play(LaggedStartMap(Indicate, circles, scale_factor=5, lag_ratio=0.3))
        self.wait()

class TestLaggedStartMapGrow(Scene):
    def construct(self):
        formula = MathTex("2026",  "=", "2", r"\times", "1013")
        self.play(LaggedStartMap(GrowFromCenter, formula, lag_ratio=0.3))
        self.wait()
```

https://github.com/user-attachments/assets/951f58d9-a641-44e9-81d5-1bc6186ed83f


https://github.com/user-attachments/assets/4e2b0253-394c-4e57-8987-afaa0d05eea6
