### PR TITLE
Fix unintended propagation of `kwargs` in `LaggedStartMap`

### LINKED ISSUE #4508: LaggedStartMap new bug (since 0.19.1)
## Description of bug / unexpected behavior
LaggedStartMap is producing an error now, but the same code works fine in 0.19.0. I guess it's releated to the refactoring of  LaggedStartMap in 0.19.1:  https://github.com/ManimCommunity/manim/pull/4214

## Expected behavior
All three scenes should be rendered, but in version 0.19.1 only one of the scenes works

## How to reproduce the issue
<details><summary>Code for reproducing the problem</summary>

```py
from manim import *


# Works fine
class TestLaggedStartMap(Scene):
    def construct(self):
        circles = VGroup(Circle() for _ in range(5)).arrange()
        self.play(LaggedStartMap(GrowFromCenter, circles, lag_ratio=0.3))
        self.wait()


# Breaks because of the formula(?)
class TestLaggedStartMap2(Scene):
    def construct(self):
        formula = MathTex("2026",  "=", "2", r"\times", "1013")
        self.play(LaggedStartMap(GrowFromCenter, formula, lag_ratio=0.3))
        self.wait()


# Breaks because of the scale_factor=2 (but it should be applied to the Indicate)
class TestLaggedStartMap3(Scene):
    def construct(self):
        circles = VGroup(Circle() for _ in range(5)).arrange()
        self.play(LaggedStartMap(Indicate, circles, scale_factor=2, lag_ratio=0.3))
        self.wait()
```

</details>

## Logs
<details><summary>Terminal output</summary>

Animation.__init__() got an unexpected keyword argument 'scale_factor'
GrowFromCenter.__init__() takes from 2 to 3 positional arguments but 5 were given   

</details>

## System specifications

<details><summary>System Details</summary>

- OS Windows 11
- Python version 3.12.1

</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution: TexLive 2023
+ Installed LaTeX packages: full installation
</details>

## Additional comments
https://discord.com/channels/581738731934056449/1019649969596153968/threads/1447988215142158558

### PR DESCRIPTION
**Pull request by irvanalhaq9**
## Overview: What does this pull request change?
Fix #4508

## Motivation and Explanation: Why and how do your changes improve the library?

Fix unintended `kwargs` propagation in `LaggedStartMap`
Ensure `kwargs` intended specifically for `animation_class` are not forwarded to the superclasses of `LaggedStartMap`, and make `lag_ratio` explicit."

### CODE REVIEW

**Comment by behackl** [comment]
Proposed one test in a reviewer commit. After writing/reading this again, it does feel a bit odd to read

```
anim = LaggedStartMap(..., rate_func=linear)
assert anim.rate_func is smooth
```

Is this fine? Should we improve it in a different way?

**Comment by irvanalhaq9** [comment]
@behackl Thanks for reviewing. I have updated the test.

**Review by behackl — APPROVED** [review]
